version: '3.8'
services:
  # Application service
  web:
    build:
      context: .
      args:
        requirements_file: requirements/local.txt
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data
    depends_on:
      - mongodb
    env_file: .env
    restart: always
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  # MongoDB Database
  mongodb:
    image: mongo:latest
    env_file: .env
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./db_confs/mongod.conf:/etc/mongo/mongod.conf
    command: [ "mongod", "--config", "/etc/mongo/mongod.conf" ]
    networks:
      - app-network

  # Redis Database
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - "8081:8080"

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
